---
- hosts: localhost
  become: yes
  tasks:
 
    #- name: update
    #  apt: update_cache=yes
 
    - name: install apache2
      apt: name=apache2 state=latest
 
    - name: restart apache2
      ansible.builtin.sysvinit: name=apache2 state=restarted
