---
- hosts: localhost
  become: yes
  tasks:
 
    #- name: update
    #  apt: update_cache=yes
 
    - name: install apache2
      apt: name=apache2 state=latest
    - name: apache2 listen on port 8081
      lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 80" line="Listen 8081" state=present
 
    - name: restart apache2
      ansible.builtin.sysvinit: name=apache2 state=stopped
