---
- hosts: localhost
  gather_facts: false
  hosts: localhost
  any_errors_fatal: true
  tasks:
    - name: install apache2
      apt: name=apache2  state=latest

    - name: apache2 listen on port 8081
      lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 80" line="Listen 8081" state=present
      notify:
        - restart apache2
  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
